### ISSUE TITLE
i have problem in using this

### ISSUE THREAD

**Issue by saltehb** [marcbux/Hi-WAY#43]
hi Marc
i do apologize for my bad english and naive question!!
im new here and im having a problem
it says "workflow structure not derivable in cuneiform" when im using HEFT.

please help me

**Comment by marcbux** [comment]
Hey,

No worries! The thing with the HEFT scheduler (or any static workflow scheduler for that matter) is, that when you run the workflow it computes a fixed schedule for which task to run on which machine. HEFT in particular needs some information of how deep a task lies in the workflow to compute a given task's "upward rank".

The trouble is that Cuneiform only shares knowledge with Hi-WAY on which tasks are currently ready to execute. In contrast, it does not provide any information on tasks that are not ready to execute yet (i.e., tasks which are still lacking some input data). In other words, a workflow's structure is not derivable in Cuneiform and, hence, Cuneiform workflows can't be scheduled statically, which is why HEFT is not supported for Cuneiform workflows.

The good news is that I'll be implementing additional schedulers in Hi-WAY in the upcoming months, so there will be more scheduling policies to choose from, even for Cuneiform workflows, in the future.

I hope this information helped somewhat and I apologize for my late response; I was out of office over the holidays.

Cheers,

Marc

**Comment by saltehb** [comment]
Hi
thanks for the reply.
if i use workflows other than cuneiform can i see some results from HEFT?
if so, give me some direction Please!
 thanks in advance.

On 1/4/17, marcbux <notifications@github.com> wrote:
> Hey,
>
> No worries! The thing with the HEFT scheduler (or any static workflow
> scheduler for that matter) is, that when you run the workflow it computes a
> fixed schedule for which task to run on which machine. HEFT in particular
> needs some information of how deep a task lies in the workflow to compute a
> given task's "upward rank".
>
> The trouble is that Cuneiform only shares knowledge with Hi-WAY on which
> tasks are currently ready to execute. In contrast, it does not provide any
> information on tasks that are not ready to execute yet (i.e., tasks which
> are still lacking some input data). In other words, a workflow's structure
> is not derivable in Cuneiform and, hence, Cuneiform workflows can't be
> scheduled statically, which is why HEFT is not supported for Cuneiform
> workflows.
>
> The good news is that I'll be implementing additional schedulers in Hi-WAY
> in the upcoming months, so there will be more scheduling policies to choose
> from, even for Cuneiform workflows, in the future.
>
> I hope this information helped somewhat and I apologize for my late
> response; I was out of office over the holidays.
>
> Cheers,
>
> Marc
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/marcbux/Hi-WAY/issues/43#issuecomment-270453933


-- 
Best Regards
Alizadeh Salteh
